### ISSUE TITLE
#19 leads to broken installation for ts modes

### ISSUE THREAD

**Issue by benotn** [Crandel/tempel-collection#20]
Hi, apparently symlinking files in your git repository does not work for an installation of the package via package.el and melpa:

```
Warning (tar): Extracted ‘~/.config/emacs/elpa/tempel-collection-20230227.1536/templates/go-ts.eld’, a link, as a normal file Disable showing Disable logging
Warning (tar): Extracted ‘~/.config/emacs/elpa/tempel-collection-20230227.1536/templates/rust-ts.eld’, a link, as a normal file Disable showing Disable logging
Warning (tar): Extracted ‘~/.config/emacs/elpa/tempel-collection-20230227.1536/templates/sh-ts.eld’, a link, as a normal file Disable showing Disable logging
```

The ts files are just empty and do not link to their non-ts counterparts.

**Comment by Crandel** [comment]
@minad Looks like we need to introduce alias support in configuration. WDYT?

**Comment by minad** [comment]
@Crandel Sure, go ahead :)

**Comment by Crandel** [comment]
I'm afraid I will not be able to do this alone. I have very basic lisp knowledge. It's enough to configure Emacs, but not enough to develop something complex, like this

**Comment by benotn** [comment]
@Crandel I can open a PR to implement this

**Comment by Crandel** [comment]
@benjaminor You are welcome. I hope @minad can review it

**Comment by minad** [comment]
@Crandel No. That's your job. ;)

If special questions come up feel free to ask.
