### ISSUE TITLE
packaging code origin mention missing

### ISSUE THREAD

**Issue by mpenet** [Crandel/tempel-collection#3]
Hi! 

Glad to see the discussion over packaging motivated you to make it available for melpa. 

I don't mind you copy/pasting what I did in that regard but you should however add a mention where you took the code from. Not only it's good mesure but if it breaks one day or if you end up improving it that'd help you remember to ping me.

Cheers

**Comment by Crandel** [comment]
@mpenet Please review this [PR](https://github.com/Crandel/tempel-collections/pull/4)
