### ISSUE TITLE
Submit package to elpa or nongnu elpa

### ISSUE THREAD

**Issue by jgarte** [Crandel/tempel-collection#32]
Hi,

What are the project milestones that would need to be reached before submitting this package to [elpa](https://elpa.gnu.org/) or [nongnu elpa](https://elpa.nongnu.org/nongnu/)?

1. More snippets?

**Comment by Crandel** [comment]
I don't want to sign any papers. For me melpa is enough

**Comment by jgarte** [comment]
Oh ok, didn't realize that it was on MELPA 🦆 

I've been using the Guix package:

https://packages.guix.gnu.org/packages/emacs-tempel-collection/0.1-0.cd9529b/
