### ISSUE TITLE
Feature Request: Lorem Ipsum Text

### ISSUE THREAD

**Issue by jgarte** [Crandel/tempel-collection#37]
Hi,

What do you think if we were to use this library to provide a tempel-like interface for lorem ipsum snippets?

https://github.com/jschaf/emacs-lorem-ipsum

**Comment by Crandel** [comment]
If you can do this, feel free to open a PR

**Comment by ispringle** [comment]
Just my two cents, this strikes me as better implemented in the lorem-ipsum project as a completion-at-point enhancement. To do it in tempel would require some guards to ensure the package is installed on the client before expanding or even evaluating the snippet. It would also be either a `:post` directive only or need a custom element declared.

There is currently an [open issue](https://github.com/jschaf/emacs-lorem-ipsum/issues/6) in that repo for a feature which I believe would require the creation of a capf, so this seems like it'd be an incidental feature of that issue being completed.
