### ISSUE TITLE
Any chance to drop the dependency on Emacs 29?

### ISSUE THREAD

**Issue by kenhuang-io** [Crandel/tempel-collection#51]
Hi,

I'm just starting to try tempel and find this could be a good starting point, but I can't install it as I'm still using Emacs 28, so I'm thinking that it would be a bit more widely used if it don't have to depend on Emacs 29.

Is it possible?

**Comment by Crandel** [comment]
No, as we need it for built-in tree-sitter modes

**Comment by kenhuang-io** [comment]
OK, thanks for the clarification.
