### ISSUE TITLE
defmethod print-object template for Common Lisp

### ISSUE THREAD

**Issue by jgarte** [Crandel/tempel-collection#57]
This is Common Lisp boiler plate that would be great to have as a template:

```lisp
(defmethod print-object ((s binary-ring-stream) stream)
  (print-unreadable-object (s stream :type t)
    (format stream "buffer=~a" (stream-buffer s))))
```

I might try to work on this soon. We currently don't have uniquely Common Lisp templates.

**Comment by Crandel** [comment]
Feel free to create a PR

**Comment by jgarte** [comment]
> Feel free to create a PR

Story of time in my life. JK ⌚ 😆 

Will try to do soon.
