### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by LionyxML** [Crandel/tempel-collection#58]
Hello there @Crandel ! Thanks for this awesome collection!

I'd like to contribute with it on the 'typescript' area.

I see we already have a js-base file. Basically i'd like to import js and keep building upon it (since typescript actually expands javascript).

Is there a way of quickly import the js-base file and extend from this one on?

It is important (I think) being able of expanding from a base file, since typescript on Emacs usually separates features into a bunch of modes (typescript-ts-mode, tsx-ts-mode, typescriptreact-mode, ...).

I see they have `typescript-ts-base-mode` as a base, so I might start it from there, but being able to import from JS would be great to avoid repetition :)

**Comment by Crandel** [comment]
> Is there a way of quickly import the js-base file and extend from this one on?

There are no such way. I will prefer to avoid such complicated logic. But if you implement it, without increasing complexity, I will consider it.

**Comment by LionyxML** [comment]
Oh man, I totally missed this answer, my bad!!

Happy to see https://github.com/Crandel/tempel-collection/blob/main/templates/js-and-typescript-ts-base.eld though, thanks :)
